version: 1
builder:
  configs:
    - documentation_targets:
        - Bylaws
        - BylawsCore
        - BylawsSemantics
        - BylawsIndexStore
        - BylawsIndex
        - BylawsInterpreter
