import Bylaws
import BylawsCore
import Foundation
import Testing

@Suite("Baseline matching")
struct BaselineMatchingTests {
  @Test("The rendered file declares the baseline and its entries")
  func rendersEntries() {
    let rendered = BaselineFile.render(name: "app", entries: [
      Baseline.Entry(
        rule: "Classes are final", declaration: "B", file: "B.swift"
      ),
      Baseline.Entry(
        rule: "Classes are final", declaration: "A", file: "A.swift"
      ),
    ])
    let expected = """
    // Generated by Bylaws. Re-run with `.record` to update this file.
    import Bylaws

    extension Baseline {
      static let app = Baseline(
        "app",
        entries: [
          Entry(
            rule: "Classes are final",
            declaration: "A",
            file: "A.swift"
          ),
          Entry(
            rule: "Classes are final",
            declaration: "B",
            file: "B.swift"
          ),
        ]
      )
    }

    """
    #expect(rendered == expected)
  }

  @Test("The rendered file escapes quotes in entry texts")
  func rendersEscapedQuotes() {
    let rendered = BaselineFile.render(name: "app", entries: [
      Baseline.Entry(
        rule: "No prints",
        declaration: #"say("hi")"#,
        file: "A.swift"
      ),
    ])
    #expect(rendered.contains(#"declaration: "say(\"hi\")""#))
  }

  @Test("An empty baseline renders with an empty entries array")
  func rendersEmpty() {
    let rendered = BaselineFile.render(name: "app", entries: [])
    #expect(rendered.contains("entries: []"))
  }

  @Test("File identities preserve paths below the project root")
  func projectRelativeFileIdentity() {
    #expect(Baseline.Entry.fileIdentity(
      for: "/project/Sources/First/Model.swift",
      relativeTo: "/project"
    ) == "Sources/First/Model.swift")
    #expect(Baseline.Entry.fileIdentity(
      for: "/project/Sources/Second/Model.swift",
      relativeTo: "/project"
    ) == "Sources/Second/Model.swift")
  }

  @Test("The recorder writes the merged entries to the baseline's file")
  func recorderWritesTheFile() async throws {
    let path = NSTemporaryDirectory()
      + "bylaws-baseline-\(UUID().uuidString).swift"
    defer { try? FileManager.default.removeItem(atPath: path) }
    let baseline = Baseline("temp", entries: [], file: path)
    let recorder = BaselineRecorder()

    let first = Baseline.Entry(
      rule: "Rule", declaration: "First", file: "A.swift"
    )
    let second = Baseline.Entry(
      rule: "Rule", declaration: "Second", file: "A.swift"
    )
    _ = try await recorder.record(
      [first],
      completedRules: ["Rule"],
      in: baseline
    )
    let total = try await recorder.record(
      [second],
      completedRules: ["Rule"],
      in: baseline
    )

    #expect(total == 2)
    let written = try String(contentsOfFile: path, encoding: .utf8)
    #expect(written.contains(#"declaration: "First""#))
    #expect(written.contains(#"declaration: "Second""#))
  }

  @Test("Recording replaces entries only for completed rules")
  func recorderPreservesIncompleteRules() async throws {
    let path = NSTemporaryDirectory()
      + "bylaws-baseline-\(UUID().uuidString).swift"
    defer { try? FileManager.default.removeItem(atPath: path) }
    let replaced = Baseline.Entry(
      rule: "Completed", declaration: "Old", file: "A.swift"
    )
    let preserved = Baseline.Entry(
      rule: "Incomplete", declaration: "StillLive", file: "B.swift"
    )
    let replacement = Baseline.Entry(
      rule: "Completed", declaration: "New", file: "C.swift"
    )
    let baseline = Baseline(
      "temp",
      entries: [replaced, preserved],
      file: path
    )
    let recorder = BaselineRecorder()

    _ = try await recorder.record(
      [replacement],
      completedRules: ["Completed"],
      in: baseline
    )

    let written = try String(contentsOfFile: path, encoding: .utf8)
    #expect(!written.contains(#"declaration: "Old""#))
    #expect(written.contains(#"declaration: "New""#))
    #expect(written.contains(#"declaration: "StillLive""#))
  }

  @Test("Separate recording sessions do not share entries")
  func recordingSessionsAreIsolated() async throws {
    let path = NSTemporaryDirectory()
      + "bylaws-baseline-\(UUID().uuidString).swift"
    defer { try? FileManager.default.removeItem(atPath: path) }
    let baseline = Baseline("temp", entries: [], file: path)
    let first = Baseline.Entry(
      rule: "Rule", declaration: "First", file: "A.swift"
    )
    let second = Baseline.Entry(
      rule: "Rule", declaration: "Second", file: "B.swift"
    )

    _ = try await BaselineRecorder().record(
      [first],
      completedRules: ["Rule"],
      in: baseline
    )
    _ = try await BaselineRecorder().record(
      [second],
      completedRules: ["Rule"],
      in: baseline
    )

    let written = try String(contentsOfFile: path, encoding: .utf8)
    #expect(!written.contains(#"declaration: "First""#))
    #expect(written.contains(#"declaration: "Second""#))
  }

  @Test("An invalid baseline name does not overwrite its file")
  func recorderRejectsInvalidName() async throws {
    let path = NSTemporaryDirectory()
      + "bylaws-baseline-\(UUID().uuidString).swift"
    defer { try? FileManager.default.removeItem(atPath: path) }
    try "original".write(toFile: path, atomically: true, encoding: .utf8)
    let baseline = Baseline("not-valid", entries: [], file: path)
    let recorder = BaselineRecorder()

    await #expect(throws: BaselineRecordingError.invalidName("not-valid")) {
      try await recorder.record(
        [],
        completedRules: [],
        in: baseline
      )
    }
    #expect(try String(contentsOfFile: path, encoding: .utf8) == "original")
  }

  @Test("A baseline entry is stale after its rule runs cleanly")
  func cleanRuleLeavesAStaleEntry() {
    let entry = Baseline.Entry(
      rule: "Classes are final",
      declaration: "OldClass",
      file: "Sources/App.swift"
    )
    let baseline = Baseline("app", entries: [entry])

    let unmatched = BaselineTrait.unmatchedEntries(
      in: baseline,
      matched: [],
      completedRules: ["Classes are final"]
    )

    #expect(unmatched == [entry])
  }

  @Test("A baseline entry is not stale when its rule did not run")
  func skippedRuleDoesNotLeaveAStaleEntry() {
    let entry = Baseline.Entry(
      rule: "Classes are final",
      declaration: "OldClass",
      file: "Sources/App.swift"
    )
    let baseline = Baseline("app", entries: [entry])

    let unmatched = BaselineTrait.unmatchedEntries(
      in: baseline,
      matched: [],
      completedRules: []
    )

    #expect(unmatched.isEmpty)
  }
}

private let knownFailure = Baseline("knownFailure", entries: [
  Baseline.Entry(
    rule: "A known violation does not fail the test",
    declaration: "",
    file: "Tests/CoreTests/Baseline/BaselineTests.swift"
  ),
])

@Suite("Baseline checking", .baseline(knownFailure))
struct BaselineCheckingTests {
  @Test("A known violation does not fail the test")
  func knownViolationDoesNotFail() {
    let value = 41
    #expect(value == 42)
  }
}

private let twoInOneFile = Codebase(root: .sources([
  "App/Screens.swift": """
  class HomeViewModel {}
  class SettingsViewModel {}
  """,
]))

private let acceptsOne = Baseline("acceptsOne", entries: [
  Baseline.Entry(
    rule: "Screen view models are final",
    declaration: "HomeViewModel",
    file: "App/Screens.swift"
  ),
])

@Suite("Baseline discrimination", .baseline(acceptsOne))
struct BaselineDiscriminationTests {
  @Test(
    "Screen view models are final",
    .annotatesViolations,
    arguments: try await twoInOneFile.classes.suffixed("ViewModel")
  )
  func screenViewModelsAreFinal(_ viewModel: Class) {
    withKnownIssue("SettingsViewModel is not in the baseline") {
      #expect(viewModel.isFinal)
    } when: {
      viewModel.name == "SettingsViewModel"
    }
  }
}

private let acceptsBoth = Baseline("acceptsBoth", entries: [
  Baseline.Entry(
    rule: "All screen view models are final",
    declaration: "HomeViewModel",
    file: "App/Screens.swift"
  ),
  Baseline.Entry(
    rule: "All screen view models are final",
    declaration: "SettingsViewModel",
    file: "App/Screens.swift"
  ),
])

@Suite("Baseline parameter collection", .baseline(acceptsBoth))
struct BaselineParameterCollectionTests {
  @Test(
    "All screen view models are final",
    .annotatesViolations,
    arguments: try await twoInOneFile.classes.suffixed("ViewModel")
  )
  func bothEntriesMatch(_ viewModel: Class) {
    #expect(viewModel.isFinal)
  }
}

private let discoveredRuleBaseline = Baseline("discoveredRule", entries: [
  Baseline.Entry(
    rule: "final-classes",
    declaration: "HomeViewModel",
    file: "App/Screens.swift"
  ),
])

private let discoveredRule = Rule("final-classes", "Classes are final") {
  try await Codebase(root: .sources([
    "App/Screens.swift": "class HomeViewModel {}",
  ])).classes.violations(of: .isFinal)
}

@Suite("Discovered rule baseline", .baseline(discoveredRuleBaseline))
struct DiscoveredRuleBaselineTests {
  @Test(
    "Reported rule uses CLI baseline identity",
    arguments: [discoveredRule]
  )
  func baselineMatches(_ rule: Rule) async throws {
    try await rule.report()
  }
}
