package enum BaselineFile {
  package static func isValidIdentifier(_ value: String) -> Bool {
    let bytes = value.utf8
    guard value != "_",
          let first = bytes.first,
          first == 95 || first >= 65 && first <= 90
          || first >= 97 && first <= 122,
          bytes.dropFirst().allSatisfy({ byte in
            byte == 95 || byte >= 65 && byte <= 90
              || byte >= 97 && byte <= 122 || byte >= 48 && byte <= 57
          }),
          !swiftKeywords.contains(value)
    else { return false }
    return true
  }

  package static func render(
    name: String,
    entries: [Baseline.Entry]
  ) -> String {
    let sorted = entries.sorted()
    let list = sorted.isEmpty
      ? "[]"
      : "[\n" + sorted.map { entry in
        """
              Entry(
                rule: \(literal(entry.rule.rawValue)),
                declaration: \(literal(entry.declaration)),
                file: \(literal(entry.file))
              ),
        """
      }.joined(separator: "\n") + "\n    ]"
    return """
    // Generated by Bylaws. Re-run with `.record` to update this file.
    import Bylaws

    extension Baseline {
      static let \(name) = Baseline(
        \(literal(name)),
        entries: \(list)
      )
    }
    """ + "\n"
  }

  private static func literal(_ value: String) -> String {
    var escaped = ""
    for scalar in value.unicodeScalars {
      switch scalar {
      case "\\": escaped += "\\\\"
      case "\"": escaped += "\\\""
      case "\n": escaped += "\\n"
      case "\t": escaped += "\\t"
      case let control
        where control.properties.generalCategory == .control
        || control.properties.generalCategory == .lineSeparator
        || control.properties.generalCategory == .paragraphSeparator:
        escaped += "\\u{\(String(control.value, radix: 16))}"
      default: escaped.unicodeScalars.append(scalar)
      }
    }
    return "\"\(escaped)\""
  }

  private static let swiftKeywords: Set<String> = [
    "Any", "Self", "actor", "as", "associatedtype", "associativity",
    "async", "await", "borrowing", "break", "case", "catch", "class",
    "consume", "consuming", "continue", "convenience", "copy", "default",
    "defer", "deinit", "didSet", "distributed", "do", "dynamic", "each",
    "else", "enum", "extension", "fallthrough", "false", "fileprivate",
    "final", "for", "func", "get", "guard", "higherThan", "if", "import",
    "in", "indirect", "infix", "init", "inout", "internal", "is",
    "isolated", "lazy", "left", "let", "lowerThan", "macro", "mutating",
    "nil", "nonisolated", "nonmutating", "none", "open", "operator",
    "optional", "override", "package", "postfix", "precedencegroup",
    "prefix", "private", "protocol", "public", "repeat", "required",
    "rethrows", "return", "right", "safe", "self", "sending", "set",
    "some", "static", "struct", "subscript", "super", "switch", "throws",
    "true", "try", "typealias", "unowned", "unsafe", "var", "weak",
    "where", "while", "willSet",
  ]
}
